[GitHub] Use Preinstalled VC++ Runtime

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -60,6 +60,7 @@ jobs:
     runs-on: windows-latest
 
     env:
+      CI_WIN_X64_RUNTIME_VERSION: "14.0"
       CI_CONFIG_TEST_PRESET: "win_x64_unit_tests"
       CI_BUILD_TEST_PRESET: "win_x64_unit_tests_build"
 
@@ -69,32 +70,21 @@ jobs:
         with:
           submodules: recursive
 
+      - name: Verify Preinstalled VC++ Runtime
+        shell: pwsh
+        run: |
+          reg query "HKLM\SOFTWARE\Microsoft\VisualStudio\${{ env.CI_WIN_X64_RUNTIME_VERSION }}\VC\Runtimes\x64" /v Version || echo "VC++ Runtime ${{ env.CI_WIN_X64_RUNTIME_VERSION }} not found!"
+
       - name: Set up Visual Studio environment
         shell: pwsh
         run: |
           echo "Setting up Visual Studio environment"
           Install-Module -Name VSSetup -Force -Scope CurrentUser
           Import-Module VSSetup
-          $vs = Get-VSSetupInstance -All -Prerelease | Select-Object -First 1
+          $vs = Get-VSSetupInstance -All | Select-Object -First 1
           & "$($vs.InstallationPath)\VC\Auxiliary\Build\vcvars64.bat"
-
-      - name: Download VC++ Redistributable
-        shell: pwsh
-        run: |
-          $url = "https://aka.ms/vs/17/release/vc_redist.x64.exe"
-          $output = "vc_redist.x64.exe"
-          Invoke-WebRequest -Uri $url -OutFile $output
-          if (!(Test-Path $output)) { throw "VS Redist x64: Download failed!" }
-
-      - name: Install VC++ Redistributable
-        shell: cmd
-        run: |
-          .\vc_redist.x64.exe /quiet /norestart || IF %ERRORLEVEL% EQU 3010 EXIT 0
-
-      - name: Verify VC++ Installation
-        shell: cmd
-        run: |
-          reg query "HKLM\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64"
+          echo "%SystemRoot%\System32\VCRUNTIME140.dll"
+          echo "%SystemRoot%\System32\MSVCP140.dll"
 
       - name: Configure CMake Preset
         shell: cmd
@@ -109,8 +99,6 @@ jobs:
       - name: Run Tests
         shell: cmd
         run: |
-          echo "%SystemRoot%\System32\VCRUNTIME140.dll"
-          echo "%SystemRoot%\System32\MSVCP140.dll"
           ctest --output-on-failure -C Release --test-dir build\${{ env.CI_CONFIG_TEST_PRESET }}\
 
       - name: Upload Test Results
